# Generated by Django 5.2.1 on 2025-06-08 12:49

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 8, 18, 19, 0, 694939)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='curd.createpost'),
        ),
    ]
