# Generated by Django 5.2.1 on 2025-06-09 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0003_createcomment_created_at_createpost_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curd.createpost'),
        ),
    ]
